<?php
//服务器IP 一般为localhost或者127.0.0.1
define('CS_Sqlserver','127.0.0.1');
//服务器端口
define('CS_Sqlport','');
//数据库名称
define('CS_Sqlname','sql_111_231_121_');
//数据库表前缀
define('CS_SqlPrefix','mu_');
//数据库用户名
define('CS_Sqluid','sql_111_231_121_');
//数据库密码
define('CS_Sqlpwd','jHFm2wecHcBHtH43');
//数据库方式
define('CS_Dbdriver','mysqli');
//Mysql数据库编码
define('CS_Sqlcharset','utf8');
//encryption_key密钥
define('CS_Encryption_Key','1k6iSGBJlXnq');
//是否开启伪静态，去掉index.php，1开启0关闭
define('CS_Web_Wjt',0);